version: "3"

services: 
  app: 
    build: . 
    container_name: cart_test
    command: npm start 
    ports:
      - "3000:3000" 
    volumes:
      - .:/usr/app ## monitoro a pasta atual . e envio as alterações para /usr/app
  